### ISSUE TITLE
Type Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by chrisyeung1121** [jkphl/gulp-svg-sprite#19]
I was trying out the library and it outputs this error on this task.

``` javascript

gulp.task('svgs', function() {
	gulp.src('svgs/*.svg')
		.pipe($.svgo())
		.pipe($.svgSprites({
			"mode": {
				"css": {
          "render": {
          	"css": true
          }
				}
			}
		}))
		.pipe(gulp.dest('svgs'))
});

```

And the error log is here: 

``` javascript

/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_modules/css-selector-parser/lib/css-selector-parser.js:172
      l = str.length;
             ^
TypeError: Cannot read property 'length' of undefined
    at new exports.CssSelectorParser.ParseContext (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_modules/css-selector-parser/lib/css-selector-parser.js:172:14)
    at CssSelectorParser.exports.CssSelectorParser.CssSelectorParser.parse (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_modules/css-selector-parser/lib/css-selector-parser.js:474:17)
    at SVGObj.<anonymous> (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/lib/svg-obj.js:238:21)
    at Array.forEach (native)
    at SVGObj._replaceIDReferences (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/lib/svg-obj.js:235:9)
    at SVGObj.<anonymous> (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/lib/svg-obj.js:192:19)
    at Array.forEach (native)
    at SVGObj.namespaceIDs (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/lib/svg-obj.js:191:68)
    at /Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/lib/svg-sprite.js:395:21
    at fn (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/Users/chrisyeung/cmd/playground/gulp/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

```

**Comment by jkphl** [comment]
Hi @chrisyeung1121,

I'm sorry but you're posting this in the wrong repo. I guess you wanted to target @shakyShane's _gulp-svg-sprite**s**_ ... ;)

Cheers,
Joschi

**Comment by chrisyeung1121** [comment]
Thanks for letting me know. :P
