### ISSUE TITLE
Cannot read property 'shapes' of undefined

### ISSUE THREAD

**Issue by smcelhinney** [jkphl/gulp-svg-sprite#24]
Getting the following error with `gulp-svg-sprite` when trying to build (1.2.1):

 
```
[ERROR] <obscured>/workspace/node_modules/gulp-svg-sprite/index.js:63
[ERROR]         if (data.css.shapes.length > 0) {
[ERROR]                     ^
[ERROR] TypeError: Cannot read property 'shapes' of undefined
[ERROR]     at Array.<anonymous> (<obscured>/workspace/node_modules/gulp-svg-sprite/index.js:63:17)
[ERROR]     at <obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/lib/svg-sprite.js:256:11
[ERROR]     at <obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/lib/svg-sprite.js:298:3
[ERROR]     at <obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/async/lib/async.js:678:13
[ERROR]     at <obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/async/lib/async.js:49:16
[ERROR]     at replenish (<obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/async/lib/async.js:304:29)
[ERROR]     at <obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/async/lib/async.js:316:29
[ERROR]     at <obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/async/lib/async.js:675:17
[ERROR]     at SVGSpriteSymbol.SVGSpriteBase._buildHTMLExample (<obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/lib/svg-sprite/mode/base.js:206:2)
[ERROR]     at SVGSpriteSymbol.<anonymous> (<obscured>/workspace/node_modules/gulp-svg-sprite/node_modules/svg-sprite/lib/svg-sprite/mode/standalone.js:119:9)
```

Any ideas?

**Comment by jkphl** [comment]
Yeah, sorry. This regression bug was introduced by PR #23 — it's already patched in the current GitHub master, a new release will follow shortly. I you don't want to wait please replace your `ìndex.js` with the [most recent one](https://github.com/jkphl/gulp-svg-sprite/blob/master/index.js).

**Comment by jkphl** [comment]
Should work again as of [release 1.2.2](https://github.com/jkphl/gulp-svg-sprite/releases/tag/v1.2.2). Sorry for the troubles.
